# Generated by Django 4.1.3 on 2022-11-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
            ],
        ),
    ]
